Tdl 9721 missing top level breadcrumb for all streams
singer-io/tap-bing-ads pull request #91
Opened 2021-10-12 11:09 UTC by dbshah1212

# Description of change
- Added top-level breadcrumb

# Manual QA steps
 - Run discover mode with and without this code and verify fields of both catalogs. 
 - There must be no missing fields.
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-10-14 07:27 UTC, savan-chovatiya commented on tap_bing_ads/__init__.py
> +            mdata = metadata.write(mdata, ('properties', field_name), 'inclusion', 'automatic')
```suggestion
    if replication_key:
        mdata = metadata.write(mdata, ('properties', replication_key), 'inclusion', 'automatic')
```

2021-10-14 07:37 UTC, dbshah1212 commented on tap_bing_ads/__init__.py
> +            mdata = metadata.write(mdata, ('properties', field_name), 'inclusion', 'automatic')
Updated

2021-12-16 07:28 UTC, karanpanchal-crest approved these changes

2021-12-16 07:29 UTC, karanpanchal-crest commented
@dbshah1212 Why is the CircleCI build failing for this PR?

2021-12-17 16:45 UTC, KrisPersonal approved these changes

2021-12-20 14:44 UTC, kspeer825 requested changes
I believe more of the standard assertions can for discovery can be applied in the tap-tester test now. Per this comment https://jira.talendforge.org/browse/TDL-9721?focusedCommentId=1003711&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1003711 it looks like replication key and primary keys are now properly set in metadata but the test is only verifying against primary keys.

2021-12-21 11:29 UTC, dbshah1212 commented
> I believe more of the standard assertions can for discovery can be applied in the tap-tester test now. Per this comment https://jira.talendforge.org/browse/TDL-9721?focusedCommentId=1003711&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1003711 it looks like replication key and primary keys are now properly set in metadata but the test is only verifying against primary keys.

Yes updated the replication keys in the base file as there is already a discrepancy in primary keys and replication keys and we already created a card for the same: https://jira.talendforge.org/browse/TDL-15816. And uncommented replication key test and it's passing now.

2021-12-21 14:18 UTC, kspeer825 approved these changes

2021-12-22 09:16 UTC, merged